version: "3.8"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/voltz-challenge
      - ./node_modules:/usr/src/voltz-challenge/node_modules
    environment:
      - NODE_ENV=development
volumes:
  db:
  node_modules:
